import MainLayout from '@/layouts/MainLayout';
import { Button } from '@mui/material';
import Head from 'next/head';
import Navbar from '../components/Navbar';

export default function Home() {
	return (
		<>
			<MainLayout>
				<Head>
					<title>Spotify Clone</title>
					<meta
						name='description'
						content='Generated by create next app'
					/>
					<meta
						name='viewport'
						content='width=device-width, initial-scale=1'
					/>
					<link rel='icon' href='/favicon.ico' />
				</Head>
				<div className='center'>
					<h1>Добро пожаловать!</h1>
					<h3>Здесь только лучшие треки</h3>
				</div>

				<style jsx>
					{`
						.center {
							margin-top: 150px;
							display: flex;
							flex-direction: column;
							align-items: center;
						}
					`}
				</style>
			</MainLayout>
		</>
	);
}
